import {
    createAsyncThunk,
    createSlice
} from '@reduxjs/toolkit';
// import from "../api";
import ResultModel from "../../model/ResultModel";
import AuthenticationModel from "../../model/AuthenticationModel";
import {ErrorModel} from "../../model/ErrorModel";
import {RootState} from "../store";
import UserModel from '../../model/UserModel';
import {BaseModel} from "../../model/BaseModel";
import {getUserInfoAPI, loginAPI} from "../api";
interface Model extends BaseModel{
    user?:UserModel;
}
const initialState:Model = {
    status: "loading"
};


export const login = createAsyncThunk<ResultModel<string>, AuthenticationModel, ErrorModel>
(
    'user/login',
    async (user: { username: string, password: string }, {rejectWithValue}) => {
        try {
            return await loginAPI(user);
        } catch (errorResult) {
            return rejectWithValue(errorResult);
        }
    },
);

export const getUserInfo = createAsyncThunk<ResultModel<UserModel>, {}, ErrorModel>
(
    'user/get',
    async ({}, {rejectWithValue}) => {
        try {
            return await getUserInfoAPI();
        } catch (errorResult) {
            return rejectWithValue(errorResult);
        }
    },
);


export const selectUser =(state: RootState) => state.userReducer.user;
export const selectUserReducer = (state: RootState) => state.userReducer;




export const userSlice = createSlice({
    name: 'user',
    initialState,
    reducers: {
        signOut: (state) => {
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(getUserInfo.pending, (state, action) => {
                state.status = 'loading';
            })
            .addCase(getUserInfo.fulfilled, (state, action) => {
                state.status = 'success';
                console.log(action.payload.result)
                state.user = action.payload.result;
            })
            .addCase(getUserInfo.rejected, (state, action) => {
                state.status = 'error';
                state.errorMsg = action.payload?.msg;
            })
    },
});
export const {signOut} = userSlice.actions;
export default userSlice.reducer;
